//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONG_WWW12
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Solicitudes
    {
        public int IdSolicitud { get; set; }
        public string Descripción { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha { get; set; } = System.DateTime.Now;
        public Nullable<int> IdTipo { get; set; }
    
        public virtual TipoSolicitud TipoSolicitud { get; set; }
    }
}
